- name: apt-get update
  command: apt-get -y update

- name: be sure kvm is installed
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - qemu-kvm
    - libvirt-clients
    - libvirt-daemon-system 
    - bridge-utils
    - virt-manager
    - ifupdown

- name: Copy network config
  template:
    src: interfaces.j2
    dest: /etc/network/interfaces
    owner: root
    group: root
    mode: 0644
  register: configure_kvmbr

- name: Add local kvm user
  user:
    name: {{ kvmhost_user }}
    shell: /bin/bash
    groups: libvirt,libvirt-qemu
    append: yes

- name: Enable and start service libvirt-bin
  service:
    name: libvirt-bin
    enabled: yes
    state: started

